// export const USER_LOADING = "USER_LOADING";
// export const USER_LOADED = "USER_LOADED";
// export const AUTH_ERROR = "AUTH_ERROR";
// export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
// export const LOGIN_FAIL = "LOGIN_FAIL";
// export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
// export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
// export const REGISTER_FAIL = "REGISTER_FAIL";
// export const GET_ERRORS = "GET_ERRORS";
// export const CLEAR_ERRORS = "CLEAR_ERRORS";
// export const SEND_USER_TOKEN_SUCCESS = " SEND_USER_TOKEN_SUCCESS";
// export const SEND_USER_TOKEN_FAILURE = " SEND_USER_TOKEN_FAILURE";
// export const FETCH_CURRENT_USER_REQUEST = "FETCH_CURRENT_USER_REQUEST";
// export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";
// export const FETCH_CURRENT_USER_FAILURE = "FETCH_CURRENT_USER_FAILURE";

export const TEST_ACTION = "TEST_ACTION";
export const TEST_ACTION2 = "TEST_ACTION2";
